### ISSUE TITLE
A minor bug which crashes the program unexpectedly.

### ISSUE THREAD

**Issue by chhanganivarun** [tacoberu/py-lifegame#1]
On line 184-188 in main.py
```python
	try:
		o = persistent.load()
	except IOError:
		self.fail('Soubor ' + filename + ' se nepodarilo otevrit.')

```
This fails on if file isn't input and the dialog box is closed.
Please merge the [now opened pull request.](https://github.com/tacoberu/py-lifegame/pull/2)

**Comment by chhanganivarun** [comment]
I've added this:
```python
		except:
			print "File not input!!"
			return 

```

**Comment by chhanganivarun** [comment]
Also please assign the issue to yourselves so that as soon as you acknowledge it, I could get to know.

**Comment by tacoberu** [comment]
fixed
